---
driver:
  name: docker_cli

transport:
  name: docker_cli

provisioner:
  name: ansible_playbook
  hosts: test-kitchen
  require_chef_for_busser: false
  require_ruby_for_busser: false
  require_ansible_repo: false
  requirements_path: test/integration/requirements.yml
  ansible_verbose: false
  ansible_verbosity: :warn
  ansible_version: latest
  ansible_host_key_checking: false
  ansible_extra_flags: <%= ENV['ANSIBLE_EXTRA_FLAGS'] %>
  update_package_repos: false
  group_vars_path: test/integration/group_vars
  env_vars:
    ANSIBLE_FORCE_COLOR: 1
  ignore_paths_from_root:
    - .bundle
    - .kitchen
    - .git
    - vendor
  idempotency_test: true

platforms:
  - name: centos-6
    driver_config:
      platform: centos
      image: geerlingguy/docker-centos6-ansible:latest
      privileged: true
      command: /sbin/init
  - name: centos-7
    driver_config:
      platform: centos
      image: geerlingguy/docker-centos7-ansible:latest
      privileged: true
      volume:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
      command: /usr/lib/systemd/systemd
  - name: debian-8
    driver_config:
      platform: debian
      image: bdellegrazie/docker-debian8-ansible:latest
      privileged: true
      volume:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
      command: /lib/systemd/systemd
  - name: ubuntu-16.04
    driver_config:
      platform: ubuntu
      image: bdellegrazie/docker-ubuntu1604-ansible:latest
      privileged: true
      #cap_add:
      #  - SYS_ADMIN
      #security_opt: seccomp=unconfined
      volume:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
      command: /lib/systemd/systemd
      stop_signal: SIGRTMIN+3
      tmpfs:
        - /run
        - /run/lock
  - name: fedora-25
    driver_config:
      platform: rhel
      image: bdellegrazie/docker-fedora25-ansible:latest
      privileged: true
      volume:
        - /sys/fs/cgroup:/sys/fs/cgroup:ro
      command: /usr/lib/systemd/systemd

suites:
  - name: default
    verifier:
      default_path: test/integration/default/serverspec

verifier:
  name: serverspec
  remote_exec: false
  patterns:
    - '**/*_spec.rb'
