---
- name: upstart service
  become: true
  template:
    src: "nginx_exporter.upstart.j2"
    dest: "/etc/init/nginx_exporter.conf"
    owner: root
    group: root
    mode: "u=rw,go=r"
  notify:
    - restart nginx_exporter
